# Prior to archiving on Netlify, production site was deployed using Travis
# This file was located at ./.travis.yml
language: ruby
cache:
  bundler: true
rvm:
- 2.5.0
branches:
  only:
  - master
env:
  global:
  - JEKYLL_ENV=production
  - secure: Zt4dEuwZRPZ/X2pDXpNCj+R8+hvAeMfXDMICx2ueiXAuMjpKzxiJmGcXuS5IpAh8u2Ja0E/ER5pXyf2PgdqaWd5MbipclaOdR67+O6RmnvRCTVnwDTS5UvsLHmRwBjHH3WE5XQR15qUFXVRIgqPKBhblsP4bQM7ZUJjuDgee2F4=]
script:
- './bin/cibuild'
before_deploy:
- openssl aes-256-cbc -K $encrypted_42ab359fa880_key -iv $encrypted_42ab359fa880_iv
  -in ./etc/travis/rsa.enc -out /tmp/rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/rsa
- ssh-add /tmp/rsa
deploy:
  provider: script
  skip_cleanup: true
  script: './bin/deploy'
  on:
    branch: master
after_success:
- curl -d "url=https%3A%2F%2Fpaulrobertlloyd.com%2Ffeed.json" https://micro.blog/ping
