title: Paul Robert Lloyd
short_title: PRL
description: Paul Robert Lloyd is an independent designer, writer and speaker based in Brighton, England.
url: https://paulrobertlloyd.com
theme_color: '#cc52cc'
background_color: '#141214'
date_format: '%e %B %Y'

# Meta
author:
  name: Paul Robert Lloyd
  url: https://paulrobertlloyd.com
  email: noreply@paulrobertlloyd.com
  avatar: https://gravatar.com/avatar/15091a37bacfa4bdd011282627eaca2b?s=512

# Source code management
scm:
  title: GitHub
  url: https://github.com/paulrobertlloyd/paulrobertlloyd.com

# Writing
kramdown:
  auto_id_stripping: true # This will become the default behaviour in kramdown 2.0

# Publishing
source: ./src
destination: ./www
include: [_indices]
profile: true
incremental: true

# Collections
collections:
  content:
    output: true
  discussions:
    output: true
  posts:
    output: true
  projects:
    output: true
  talks:
    output: true

# Defaults
defaults:
  - scope:
      type: content
    values:
      permalink: :path
      layout: content

  - scope:
      type: discussions
    values:
      permalink: /:categories/:year/:month/:title/discussion
      layout: discussion

  - scope:
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      image:
        preset: wide

  - scope:
      type: posts
      path: "_posts/galleries"
    values:
      category: photos
      layout: gallery
      theme: dark

  - scope:
      type: posts
      path: "_posts/links"
    values:
      category: links
      layout: link

  - scope:
      type: posts
      path: "_posts/notes"
    values:
      category: notes
      layout: note

  - scope:
      type: projects
    values:
      permalink: /projects/:title
      layout: project

  - scope:
      type: talks
    values:
      permalink: /talks/:year/:month/:title
      layout: talk

# Images
images:
  default:
    sources:
      - width: 480
        quality: 80
      - width: 800
        quality: 80
  thumbnail:
    sizes: '33vw'
    sources:
      - width: 240
        quality: 80
      - width: 320
        quality: 80
  supporting:
    sizes: '50vw'
    sources:
      - width: 480
        quality: 80
      - width: 640
        quality: 80
      - width: 960
        quality: 80
  showcase:
    sources:
      - width: 768
        quality: 80
      - width: 1024
        quality: 88
      - width: 1280
        quality: 88
  wide:
    sources:
      - width: 800
        height: 450
        quality: 80
      - width: 1024
        height: 576
        quality: 88
      - width: 1280
        height: 675
        quality: 88
  anamorphic:
    sources:
      - width: 1020
        height: 425
        quality: 88
      - width: 720
        height: 300
        quality: 80
      - width: 1200
        height: 500
        quality: 88

# Plugin: jekyll-assets
assets:
  sources:
    - _assets/fonts
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/vectors

# Plugin: jekyll-paginate-v2
pagination:
  enabled: true
  title: ':title'
  permalink: '/:num'
  sort_reverse: true
  per_page: 15

# Plugin: jekyll-archives
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: archive-year
    month: archive-month
    tag: archive-tag
  permalinks:
    year: /:year/
    month: /:year/:month/
    tag: /tags/:name.html

# Plugin: jekyll-crosspost-to-medium
jekyll-crosspost_to_medium:
  cache: ./src/_data/
  status: draft
  license: cc-40-by-nc-sa
