title: Paul Robert Lloyd
short_title: PRL
description: Paul Robert Lloyd is an independent designer, writer and speaker based in Brighton, England.
url: https://paulrobertlloyd.com
theme_color: '#cc52cc'
background_color: '#141214'

# Meta
author:
  name: Paul Robert Lloyd
  url: https://paulrobertlloyd.com
  email: noreply@paulrobertlloyd.com
  avatar: https://gravatar.com/avatar/15091a37bacfa4bdd011282627eaca2b?s=512

# Source code management
scm:
  title: GitHub
  url: https://github.com/paulrobertlloyd/paulrobertlloyd.com

# Writing
kramdown:
  auto_id_stripping: true # This will become the default behaviour in kramdown 2.0

# Publishing
source: ./src
destination: ./www
include: [_indices]

# Collections
collections:
  content:
    output: true
    permalink: :path
  discussions:
    output: true
    permalink: /:year/:month/:title/discussion
  links:
    output: true
    permalink: /:year/:month/:title
  galleries:
    output: true
    permalink: /:year/:month/:title
  posts:
    output: true
    permalink: /:year/:month/:title
  projects:
    output: true
    permalink: /projects/:title
  talks:
    output: true
    permalink: /talks/:title

# Defaults
defaults:
  - scope:
      type: content
    values:
      layout: content

  - scope:
      type: discussions
    values:
      layout: discussion

  - scope:
      type: links
    values:
      layout: entry
      journal: true

  - scope:
      type: galleries
    values:
      layout: gallery
      journal: true
      theme: dark

  - scope:
      type: posts
    values:
      layout: entry
      journal: true
      image:
        preset: wide

  - scope:
      type: projects
    values:
      layout: project

  - scope:
      type: talks
    values:
      layout: talk

# Images
images:
  default:
    sources:
      - width: 480
        quality: 80
      - width: 800
        quality: 80
  thumbnail:
    sizes: '33vw'
    sources:
      - width: 240
        quality: 80
      - width: 320
        quality: 80
  supporting:
    sizes: '50vw'
    sources:
      - width: 480
        quality: 80
      - width: 640
        quality: 80
  showcase:
    sources:
      - width: 768
        quality: 80
      - width: 1024
        quality: 88
      - width: 1280
        quality: 88
  wide:
    sources:
      - width: 800
        height: 450
        quality: 80
      - width: 1024
        height: 576
        quality: 88
      - width: 1280
        height: 675
        quality: 88
  anamorphic:
    sources:
      - width: 1020
        height: 425
        quality: 88
      - width: 720
        height: 300
        quality: 80
      - width: 1200
        height: 500
        quality: 88

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Plugin: jekyll-assets
assets:
  sources:
    - _assets/fonts
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/vectors

# Plugin: jekyll-paginate-v2
pagination:
  enabled: true
  title: ':title'
  permalink: '/:num'
  sort_reverse: true
  per_page: 15

# Plugin: jekyll-archives
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: index-archive-year
    month: index-archive
    tag: index-archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    tag: /tags/:name.html

# Plugin: jekyll-crosspost-to-medium
jekyll-crosspost_to_medium:
  cache: ./src/_data/
  status: draft
  license: cc-40-by-nc-sa
